### ISSUE TITLE
Build error: Sundials is not downloaded from the website anymore

### ISSUE THREAD

**Issue by prcastro** [JuliaLang/Sundials.jl#36]
When I try to build the package on Julia 0.3, I get:

```julia
 julia> Pkg.build("Sundials")
 INFO: Building Sundials
 INFO: Attempting to Create directory /home/paulo/.julia/v0.3/Sundials/deps/downloads
 INFO: Directory /home/paulo/.julia/v0.3/Sundials/deps/downloads already created
 INFO: Downloading file http://computation.llnl.gov/casc/sundials/download/code/sundials-2.5.0.tar.gz
 INFO: Done downloading file http://computation.llnl.gov/casc/sundials/download/code/sundials -2.5.0.tar.gz
 INFO: Attempting to Create directory /home/paulo/.julia/v0.3/Sundials/deps/src
 INFO: Directory /home/paulo/.julia/v0.3/Sundials/deps/src already created
 INFO: Attempting to Create directory /home/paulo/.julia/v0.3/Sundials/deps
 INFO: Directory /home/paulo/.julia/v0.3/Sundials/deps already created
 INFO: Attempting to Create directory /home/paulo/.julia/v0.3/Sundials/deps/src/sundials-2.5.0

 gzip: stdin: not in gzip format
 tar: Child returned status 1
 tar: Error is not recoverable: exiting now
 ==============================[ ERROR: Sundials ]===============================
 
 failed process: Process(`tar xzf /home/paulo/.julia/v0.3/Sundials/deps/downloads/sundials- 2.5.0.tar.gz --directory=/home/paulo/.julia/v0.3/Sundials/deps/src`, ProcessExited(2)) [2]
 while loading /home/paulo/.julia/v0.3/Sundials/deps/build.jl, in expression starting on line 37
 
 ================================================================================
 
 ================================[ BUILD ERRORS ]================================

WARNING: Sundials had build errors.

 - packages with build errors remain installed in /home/paulo/.julia/v0.3
 - build a package and all its dependencies with `Pkg.build(pkg)`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by brk00** [comment]
It turns out that the direc downoad is not available from the website anymore. The users must pass throught a registraon form to access the download.

I suggest uploading to dropbox the last and change it when new versions launch.

**Comment by ViralBShah** [comment]
We can use Debian package source

https://packages.debian.org/sid/libsundials-cvodes2

**Comment by ViralBShah** [comment]
http://ftp.de.debian.org/debian/pool/main/s/sundials/sundials_2.5.0.orig.tar.gz

**Comment by tkelman** [comment]
i think this was resolved by #35, might just need to be tagged?

**Comment by tkelman** [comment]
@brk00 What version of the Sundials package are you on? It looks like the updated url from 9048a493436edf327d884932aa10958297060612 should be included in v0.1.2.

**Comment by ivarne** [comment]
Bump!

**Comment by acroy** [comment]
`Pkg.add("Sundials")` works for me after `Pkg.update()`, but you might have to delete the `~/.julia/v0.X/Sundials` directory where `X=3` or `4` (you have to delete at least the tarball in `deps/downloads/`).

**Comment by acroy** [comment]
Just tried it again and it works. If there are still problems please reopen this issue or create a new one.

**Comment by SCR1** [comment]
I just got this error trying to get this up and running for the first time. Not sure this is still an issue or if I'm just doing something horriby wrong?

**Comment by ChrisRackauckas** [comment]
It's probably a different issue. Can you open a new issue and post the full error?

**Comment by SCR1** [comment]
Now in #121. You're right it looks like a connectivity issue perhaps. Ever seen this before?
