### ISSUE TITLE
Opaque pointer type void* should be represented with Ptr{Void}, not Ptr{None}

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/Sundials.jl#47]
Opaque pointer type `void*` should be represented with `Ptr{Void}`, not `Ptr{None}`, because using `Ptr{None}` goes against what Julia manual says (http://julia.readthedocs.org/en/latest/manual/calling-c-and-fortran-code/).

`Ptr{None}` is incorrectly used all over cvodes, as well as the other components.

**Comment by acroy** [comment]
Changed in #57.
