### ISSUE TITLE
Sundials problem memory is not garbage collected

### ISSUE THREAD

**Issue by ikirill** [JuliaLang/Sundials.jl#49]
Ideally, there should be a garbage-collected wrapper looking something like this:

    type CVmem
      handle :: Ptr{Void}
      function CVmem(lmm::Cint, iter::Cint)
        mem = new(CVodeCreate(lmm, iter))
        mem.handle == C_NULL && error("CVodeCreate failed")
        finalizer(mem, CVodeFree)
        mem
      end
    end

    convert(::Type{Ptr{Void}}, mem::CVmem) = mem.handle

    CVodeFree(mem::CVmem) = ccall((:CVodeFree, Sundials.libsundials_cvodes), Void, (Ptr{Ptr{Void}},), &mem)

Of course, the garbage collector won't always collect the memory aggressively if Sundials uses a lot of it, but it is much more "julia-like" to try to collect these pointers than to expect the user to call create/free pairs.

**Comment by acroy** [comment]
See #29. If you happen to have some time it would be great if you could take care of finishing #29. Shouldn't be much left to do ...

**Comment by axsk** [comment]
Maybe one should close this issue, since its all in #29?

**Comment by acroy** [comment]
The simplified interface now uses `CVodeFree` et al to free memory. The `finializer` idea is covered in #29.
