### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by crbinz** [JuliaLang/Sundials.jl#53]
I currently have a package that requires the latest Sundials master, because it relies on the fix from #42. Is it possible to tag a new release so I can use it in my `REQUIRE`? I'm happy to do this, assuming I can figure out the process.

**Comment by acroy** [comment]
Done. The new version should be v"0.1.3". Let us know if there are any problems.

**Comment by crbinz** [comment]
Thanks! However, I don't see v0.1.3 showing up anywhere...

**Comment by ViralBShah** [comment]
Did you do `Pkg.update()`?

**Comment by ViralBShah** [comment]
Actually, I don't see it on METADATA either.

**Comment by acroy** [comment]
Sorry, it's my fault. I was in a hurry and forgot `Pkg.publish()` ... doing this now.

**Comment by acroy** [comment]
Once JuliaLang/METADATA.jl#3183 is merged this should work.

**Comment by crbinz** [comment]
I see it now, thanks again.
